name: Run Jest Tests

on:
  push:
    branches: [main, inventory-backend]
  pull_request:
    branches: [main, inventory-backend]

jobs:
  # UNIT TEST JOB
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Product Unit Tests
        run: npm test -- productController.test.js

      - name: Run Stock Unit Tests
        run: npm test -- stockController.test.js

      - name: Run Orders Unit Tests
        run: npm test -- orderController.test.js

      - name: Run Equipment Unit Tests
        run: npm test -- equipmentController.test.js

  # INTEGRATION TEST JOB
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Product Integration Tests
        run: npm test -- productRoutes.test.js

      - name: Run Stock Integration Tests
        run: npm test -- stockRoutes.test.js

      - name: Run Order Integration Tests
        run: npm test -- orderRoutes.test.js

      - name: Run Equipment Integration Tests
        run: npm test -- equipmentRoutes.test.js
